Repository microsoft/vscode-react-native, pull requests merged in 2018-12, with the labels that each got.

#848 Add i18n to basic commands
  i18n/chs/package.i18n.json
  i18n/cht/package.i18n.json
  i18n/csy/package.i18n.json
  i18n/deu/package.i18n.json
  i18n/esn/package.i18n.json
  i18n/fra/package.i18n.json
  i18n/ita/package.i18n.json
  i18n/jpn/package.i18n.json
  i18n/kor/package.i18n.json
  i18n/plk/package.i18n.json
  i18n/ptb/package.i18n.json
  i18n/rus/package.i18n.json
  i18n/trk/package.i18n.json
  package.json
  package.nls.it.json
  package.nls.json
Labels: externalization

#832 Show login notification as modal window
  src/extension/exponent/exponentHelper.ts
  src/extension/exponent/exponentPlatform.ts
Labels: debugger, expo

#862 Add tests for errorHelper.ts, fix messages for warnings, fix gulp task build asynchronicity
  gulpfile.js
  src/common/error/errorHelper.ts
  src/common/error/internalError.ts
  test/common/error/errorHelper.test.ts
Labels: tests

#865 Add i18n for string literals from files in extension folder, refactor FailurePatterns to match to the corresponding error codes and strings
  src/common/error/errorStrings.ts
  src/common/error/internalErrorCode.ts
  src/common/outputVerifier.ts
  src/extension/android/adb.ts
  src/extension/android/androidPlatform.ts
  src/extension/android/logCatMonitor.ts
  src/extension/commandPaletteHandler.ts
  src/extension/exponent/exponentHelper.ts
  src/extension/exponent/exponentPlatform.ts
  src/extension/exponent/xdlInterface.ts
  src/extension/generalMobilePlatform.ts
  src/extension/ios/iOSDebugModeManager.ts
  src/extension/ios/iOSPlatform.ts
  src/extension/ios/plistBuddy.ts
  src/extension/ios/simulatorPlist.ts
  src/extension/openFileAtLocation.ts
  src/extension/packagerStatusIndicator.ts
  src/extension/qrCodeContentProvider.ts
  src/extension/rn-extension.ts
  src/extension/windows/windowsPlatform.ts
  src/extension/windows/wpfPlatform.ts
  test/extension/android/androidPlatform.test.ts
Labels: localization

#877 Increase timeout for appworker test
  test/debugger/appWorker.test.ts
Labels: tests
