Repository microsoft/vscode-react-native, pull requests merged in 2019-10, with the labels that each got.

#1124 Prepare for 0.12.0
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease

#1130 Prepare for 0.12.1
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease

#1128 Bump RN version for smoke tests
  test/smoke/config.json
Labels: tests

#1140 Fix Hermes scenarios names, fix port argument handling
  doc/debugging.md
  package.json
  package.nls.json
  src/debugger/direct/directDebugAdapter.ts
  src/extension/debugConfigurationProvider.ts
  test/smoke/resources/launch.json
  test/smoke/src/debugAndroid.test.ts
Labels: hermes

#1151 Prepare for 0.13.0
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease
