Repository microsoft/vscode-react-native, pull requests merged in 2019-07, with the labels that each got.

#1045 Prepare for 0.10.1
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease

#1048 Fix extension context android tests on VS Code 1.36
  .gitignore
  package-lock.json
  package.json
  test/extension/android/androidPlatform.test.ts
Labels: tests

#1049 Fix appworker test for Node 10
  test/debugger/appWorker.test.ts
Labels: tests

#1050 Fix CVE-2019-10744, WS-2018-0236 security vulnerabilities
  package-lock.json
  package.json
Labels: security

#1052 [Smoke tests] Fix CVE-2019-10744 security vulnerability
  test/smoke/package.json
  test/smoke/src/spectron/application.ts
  test/smoke/yarn.lock
Labels: tests

#1055 Fix set-value and mixin-deep vulnerabilities
  package-lock.json
Labels: security

#1053 Prepare for 0.10.2
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease
