Repository microsoft/vscode-react-native, pull requests merged in 2019-04, with the labels that each got.

#964 [Smoke tests] Add typings for some packages
  test/smoke/package.json
  test/smoke/yarn.lock
Labels: tests

#965 [Smoke tests] Add dropwin dir to git
  test/resources/drop-win/.gitkeep
Labels: tests

#968 [Smoke tests] Tests refactoring, fix css selectors for VS Code 1.33
  test/smoke/.gitignore
  test/smoke/resources/drop-win/.gitkeep
  test/smoke/src/areas/debug/debug.ts
  test/smoke/src/areas/explorer/explorer.ts
  test/smoke/src/debugAndroid.test.ts
  test/smoke/src/helpers/appiumHelper.ts
  test/smoke/src/helpers/setupEnvironmentHelper.ts
  test/smoke/src/main.ts
  test/smoke/src/spectron/application.ts
Labels: tests

#970 [Smoke tests] Improved Expo URL retrieve
  test/smoke/src/debugAndroid.test.ts
Labels: tests

#972 [Smoke tests] Add multi reporter
  test/smoke/mochaReporterConfig.json
  test/smoke/package.json
  test/smoke/yarn.lock
Labels: tests

#971 [Smoke tests] Add tslint for the tests
  .vscode/launch.json
  .vscode/tasks.json
  test/smoke/package.json
  test/smoke/src/areas/editor/peek.ts
  test/smoke/src/debugAndroid.test.ts
  test/smoke/src/helpers/appiumHelper.ts
  test/smoke/src/helpers/setupEnvironmentHelper.ts
  test/smoke/src/helpers/smokeTestsConstants.ts
  test/smoke/src/main.ts
  test/smoke/tsconfig.json
  test/smoke/tslint.json
  test/smoke/yarn.lock
Labels: tests

#966 [Smoke tests] Added iOS simulator launch step
  test/smoke/src/helpers/iosSimulatorHelper.ts
  test/smoke/src/helpers/setupEnvironmentHelper.ts
  test/smoke/src/main.ts
Labels: tests

#973 [Smoke tests] Smoke tests refactoring
  test/smoke/package.json
  test/smoke/src/areas/debug/debug.ts
  test/smoke/src/debugAndroid.test.ts
  test/smoke/src/helpers/androidEmulatorHelper.ts
  test/smoke/src/helpers/appiumHelper.ts
  test/smoke/src/helpers/iosSimulatorHelper.ts
  test/smoke/src/helpers/setupEnvironmentHelper.ts
  test/smoke/src/helpers/shared.ts
  test/smoke/src/helpers/smokeTestsConstants.ts
  test/smoke/src/helpers/utilities.ts
  test/smoke/src/helpers/vsCodeHelper.ts
  test/smoke/src/main.ts
  test/smoke/src/spectron/application.ts
  test/smoke/test/mocha.opts
  test/smoke/yarn.lock
Labels: refactoring, tests

#975 Add information about potential problems with React Native sourcemaps
  README.md
Labels: documentation

#979 Prepare for 0.9.2
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease

#980 [Smoke tests] Update from master
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
  src/debugger/appWorker.ts
  src/extension/qrCodeContentProvider.ts
  test/debugger/appWorker.test.ts
Labels: tests

#986 [Docs] Adding a bug to known issues in the readme for adding configuration in VSCode
  README.md
Labels: documentation

#987 Fix known issues table
  README.md
Labels: documentation

#984 [Smoke tests] Add collecting logs from the extension
  test/smoke/package.json
  test/smoke/src/main.ts
  test/smoke/src/spectron/application.ts
  test/smoke/yarn.lock
Labels: tests
