Repository microsoft/vscode-react-native, pull requests merged in 2019-12, with the labels that each got.

#1176 Fix Expo 36 workflow for Expo Android on macOS
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/src/debugIos.test.ts
  test/smoke/package/src/helpers/appiumHelper.ts
Labels: tests

#1178 Update smoke tests docs
  test/smoke/docs/perform-manually.md
  test/smoke/docs/run-locally.md
Labels: tests

#1181 Update environment preparation for Hermes smoke tests, bump smoke tests deps
  test/smoke/automation/yarn.lock
  test/smoke/package/config.json
  test/smoke/package/package.json
  test/smoke/package/resources/HermesReactNativeSample/react.gradle
  test/smoke/package/src/helpers/setupEnvironmentHelper.ts
  test/smoke/package/yarn.lock
Labels: security, tests

#1184 Remove redundant cpx package
  test/smoke/automation/package.json
  test/smoke/automation/yarn.lock
Labels: security, tests

#1187 Fix displaying of VM_unknown calls in Call Stack for Hermes debugger
  src/debugger/direct/directDebugAdapter.ts
Labels: hermes
