Repository microsoft/vscode-react-native, pull requests merged in 2019-11, with the labels that each got.

#1161 Prepare for 0.13.1
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease

#1165 Fix Handlebars security vulnerability
  package-lock.json
  test/smoke/config.json
Labels: security

#1166 Add support for Haul packager 0.15+
  src/common/reactNativeProjectHelper.ts
  src/debugger/appWorker.ts
  src/debugger/forkedAppWorker.ts
  src/debugger/sourceMap.ts
  test/debugger/appWorker.test.ts
  test/debugger/sourceMap.test.ts
Labels: haul

#1168 Prepare for 0.13.2
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease

#1170 Adapt Expo smoke tests for new VS Code driver
  gulpfile.js
  package.json
  test/smoke/automation/package.json
  test/smoke/automation/src/code.ts
  test/smoke/automation/src/debug.ts
  test/smoke/automation/src/editors.ts
  test/smoke/automation/yarn.lock
  test/smoke/package/package.json
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/src/debugIos.test.ts
  test/smoke/package/src/helpers/appiumHelper.ts
  test/smoke/package/src/helpers/utilities.ts
  test/smoke/package/src/main.ts
  test/smoke/package/yarn.lock
Labels: tests

#1172 [Smoke tests] Update from master
  CHANGELOG.md
  README.md
  doc/containerization.md
  package-lock.json
  package.json
  release/LICENSE.txt
  release/ThirdPartyNotices.txt
  src/common/commandExecutor.ts
  src/common/node/package.ts
  src/common/packager.ts
  src/common/reactNativeProjectHelper.ts
  src/common/telemetry.ts
  src/common/telemetryHelper.ts
  src/debugger/appWorker.ts
  src/debugger/direct/directDebugAdapter.ts
  src/debugger/forkedAppWorker.ts
  src/debugger/nodeDebugWrapper.ts
  src/debugger/scriptImporter.ts
  src/debugger/sourceMap.ts
  src/extension/android/androidPlatform.ts
  src/extension/commandPaletteHandler.ts
  src/extension/exponent/exponentHelper.ts
  src/extension/exponent/exponentPlatform.ts
  src/extension/extensionServer.ts
  src/extension/ios/iOSPlatform.ts
  src/extension/ios/plistBuddy.ts
  src/extension/launchArgs.ts
  src/extension/rn-extension.ts
  src/extension/windows/windowsPlatform.ts
  src/extension/windows/wpfPlatform.ts
  src/typings/plist-with-patches/plist-with-patches.d.ts
  src/typings/sinon/sinon.d.ts
  src/typings/strip-json-comments/strip-json-comments.d.ts
  src/typings/winreg/winreg.d.ts
  test/common/reactNativeProjectHelper.test.ts
  test/debugger/appWorker.test.ts
  test/debugger/assets/debuggerWorker.ts
  test/debugger/sourceMap.test.ts
  test/extension/android/androidPlatform.test.ts
  test/extension/ios/plistBuddy.test.ts
  test/resources/sampleReactNative022Project/package.json
  test/smoke/package/config.json
Labels: tests

#1171 Fix Handlebars security vulnerability
  package-lock.json
Labels: security
