Repository microsoft/vscode-react-native, pull requests merged in 2019-01, with the labels that each got.

#880 Fix debugger url for haul projects
  src/debugger/scriptImporter.ts
Labels: haul

#891 Add vscode smoke test framework
  ThirdPartyNotices.txt
  test/smoke/.gitignore
  test/smoke/Audit.md
  test/smoke/README.md
  test/smoke/package.json
  test/smoke/src/application.ts
  test/smoke/src/areas/activitybar/activityBar.ts
  test/smoke/src/areas/css/css.test.ts
  test/smoke/src/areas/debug/debug.test.ts
  test/smoke/src/areas/debug/debugSmoke.ts
  test/smoke/src/areas/editor/editor.test.ts
  test/smoke/src/areas/editor/editor.ts
  test/smoke/src/areas/editor/editors.ts
  test/smoke/src/areas/editor/peek.ts
  test/smoke/src/areas/explorer/explorer.test.ts
  test/smoke/src/areas/explorer/explorer.ts
  test/smoke/src/areas/extensions/extensions.test.ts
  test/smoke/src/areas/extensions/extensions.ts
  test/smoke/src/areas/git/git.test.ts
  test/smoke/src/areas/git/scm.ts
  test/smoke/src/areas/multiroot/multiroot.test.ts
  test/smoke/src/areas/preferences/keybindings.ts
  test/smoke/src/areas/preferences/preferences.test.ts
  test/smoke/src/areas/preferences/settings.ts
  test/smoke/src/areas/problems/problems.ts
  test/smoke/src/areas/quickinput/quickinput.ts
  test/smoke/src/areas/quickopen/quickopen.ts
  test/smoke/src/areas/search/search.test.ts
  test/smoke/src/areas/search/search.ts
  test/smoke/src/areas/statusbar/statusbar.test.ts
  test/smoke/src/areas/statusbar/statusbar.ts
  test/smoke/src/areas/terminal/terminal.test.ts
  test/smoke/src/areas/terminal/terminal.ts
  test/smoke/src/areas/workbench/data-loss.test.ts
  test/smoke/src/areas/workbench/data-migration.test.ts
  test/smoke/src/areas/workbench/launch.test.ts
  test/smoke/src/areas/workbench/localization.test.ts
  test/smoke/src/areas/workbench/viewlet.ts
  test/smoke/src/areas/workbench/workbench.ts
  test/smoke/src/logger.ts
  test/smoke/src/main.ts
  test/smoke/src/utils.ts
  test/smoke/src/vscode/code.ts
  test/smoke/tsconfig.json
  test/smoke/yarn.lock
Labels: tests

#892 Set up CI with Azure Pipelines for smoke tests
  test/smoke/azure-pipelines.yml
Labels: tests

#893 Add boilerplate for running tests
  test/smoke/azure-pipelines.yml
Labels: tests

#895 Update extension description
  package.nls.json
Labels: documentation
