Repository microsoft/vscode-react-native, pull requests merged in 2019-03, with the labels that each got.

#886 Fix broken sentence
  README.md
Labels: documentation

#924 add missing doublequotes
  doc/customization.md
Labels: documentation

#923 [Smoke tests] Fix several issues
  .vscode/launch.json
  .vscode/tasks.json
  gulpfile.js
  test/smoke/package.json
  test/smoke/src/helpers/appiumHelper.ts
  test/smoke/src/helpers/setupEnvironmentHelper.ts
  test/smoke/src/helpers/shared.ts
  test/smoke/src/main.ts
  test/smoke/yarn.lock
Labels: tests

#937 Fix ios debugging on RN 0.59
  release/AdditionalAttributions.txt
  src/extension/ios/iOSDebugModeManager.ts
  src/extension/ios/iOSPlatform.ts
  src/extension/ios/plistBuddy.ts
  src/extension/ios/simulatorPlist.ts
  test/extension/ios/plistBuddy.test.ts
  test/extension/ios/simulatorPlist.test.ts
Labels: debugger, iOS

#925 [Smoke tests] Add Debug Expo test for Android
  .gitignore
  gulpfile.js
  test/smoke/resources/ExpoSample/App.js
  test/smoke/resources/ReactNativeSample/App.js
  test/smoke/src/areas/debug/debug.ts
  test/smoke/src/areas/workbench/workbench.ts
  test/smoke/src/debugAndroid.test.ts
  test/smoke/src/helpers/appiumHelper.ts
  test/smoke/src/helpers/expoAppHelper.ts
  test/smoke/src/helpers/setupEnvironmentHelper.ts
  test/smoke/src/helpers/smokeTestsConstants.ts
  test/smoke/src/main.ts
  test/smoke/src/spectron/application.ts
Labels: tests

#948 [Smoke tests] Fix transliteration
  test/smoke/src/spectron/application.ts
Labels: tests

#949 [Smoke tests] Fix minor issues
  .vscode/tasks.json
  test/smoke/src/areas/debug/debug.ts
  test/smoke/src/main.ts
  test/smoke/src/spectron/application.ts
  test/smoke/src/spectron/client.ts
Labels: tests

#954 Update docs section for running pure React Native apps via Expo
  doc/expo.md
  src/extension/exponent/exponentHelper.ts
Labels: documentation

#942 [Smoke tests] Add test for pure RN debugging via Expo
  .gitignore
  gulpfile.js
  test/smoke/.gitignore
  test/smoke/src/debugAndroid.test.ts
  test/smoke/src/helpers/appiumHelper.ts
  test/smoke/src/helpers/setupEnvironmentHelper.ts
  test/smoke/src/helpers/smokeTestsConstants.ts
  test/smoke/src/main.ts
Labels: tests

#953 [Smoke tests] Fix another smoke tests issues on Mac
  test/smoke/package.json
  test/smoke/src/areas/debug/debug.ts
  test/smoke/src/debugAndroid.test.ts
  test/smoke/src/helpers/appiumHelper.ts
  test/smoke/src/helpers/setupEnvironmentHelper.ts
  test/smoke/src/helpers/utilities.ts
  test/smoke/src/main.ts
  test/smoke/test/mocha.opts
  test/smoke/yarn.lock
Labels: tests

#956 [Smoke tests] Refactor call React Native DevMenu logic
  test/smoke/src/helpers/appiumHelper.ts
Labels: tests

#958 Fix test suites names for better readability
  test/smoke/.gitignore
  test/smoke/src/debugAndroid.test.ts
  test/smoke/src/main.ts
Labels: tests
