Repository microsoft/vscode-react-native, pull requests merged in 2020-11, with the labels that each got.

#1454 Prepare for 1.1.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: prerelease

#1448 Add macOS smoke test
  .ci/smoke/smoke-tests-mac.yml
  test/smoke/package/.mocharc.js
  test/smoke/package/config.json
  test/smoke/package/package.json
  test/smoke/package/resources/MacOSReactNativeSample/App.js
  test/smoke/package/resources/launch.json
  test/smoke/package/src/debugIos.test.ts
  test/smoke/package/src/debugMacOS.test.ts
  test/smoke/package/src/helpers/configHelper.ts
  test/smoke/package/src/helpers/setupEnvironmentHelper.ts
  test/smoke/package/src/helpers/smokeTestsConstants.ts
  test/smoke/package/src/main.ts
  test/smoke/package/test/mocha.opts
Labels: tests

#1449 Smoke tests logging improvement
  test/smoke/package/package.json
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/src/debugIos.test.ts
  test/smoke/package/src/debugMacOS.test.ts
  test/smoke/package/src/debugWindows.test.ts
  test/smoke/package/src/helpers/androidEmulatorHelper.ts
  test/smoke/package/src/helpers/appiumHelper.ts
  test/smoke/package/src/helpers/configHelper.ts
  test/smoke/package/src/helpers/iosSimulatorHelper.ts
  test/smoke/package/src/helpers/setupEnvironmentHelper.ts
  test/smoke/package/src/helpers/smokeTestLogger.ts
  test/smoke/package/src/helpers/utilities.ts
  test/smoke/package/src/helpers/vsCodeHelper.ts
  test/smoke/package/src/localization.test.ts
  test/smoke/package/src/main.ts
  test/smoke/package/yarn.lock
Labels: enhancement, tests
