Repository microsoft/vscode-react-native, pull requests merged in 2020-05, with the labels that each got.

#1282 Enhance Hermes apps debugging
  src/cdp-proxy/reactNativeCDPProxy.ts
  src/debugger/debugSessionBase.ts
  src/debugger/direct/directDebugSession.ts
  src/debugger/rnDebugSession.ts
Labels: hermes, js-debug-migration

#1279 Update Expo app template code
  test/smoke/package/resources/ExpoSample/App.js
  test/smoke/package/src/helpers/appiumHelper.ts
Labels: tests

#1277 feat: issue templates
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
Labels: documentation

#1284 Fix links in Table of Contents, typo
  README.md
Labels: documentation

#1283 Merging master and dev
  .ci/common-validation.yml
  .ci/master-pipeline.yml
  .ci/pr-pipeline.yml
  .ci/smoke/smoke-tests-common-validation.yml
  .ci/smoke/smoke-tests-linux.yml
  .ci/smoke/smoke-tests-mac.yml
  .ci/smoke/smoke-tests-windows.yml
  CHANGELOG.md
  README.md
  doc/containerization.md
  doc/customization.md
  doc/debugging.md
  doc/expo.md
  doc/tasks.md
  gulpfile.js
  package-lock.json
  package.json
  package.nls.json
  release/ThirdPartyNotices.txt
  src/common/packager.ts
  src/common/utils.ts
  src/extension/android/androidPlatform.ts
  src/extension/appLauncher.ts
  src/extension/exponent/exponentPlatform.ts
  src/extension/generalMobilePlatform.ts
  src/extension/ios/iOSPlatform.ts
  src/extension/ios/plistBuddy.ts
  src/extension/windows/windowsPlatform.ts
  src/extension/windows/wpfPlatform.ts
  test/extension/generalMobilePlatform.test.ts
  test/extension/ios/iOSPlatform.test.ts
  test/extension/ios/plistBuddy.test.ts
  test/localization/index.ts
  test/resources/auxiliaryFiles/buildSettings.txt
  test/smoke/automation/package.json
  test/smoke/automation/src/debug.ts
  test/smoke/automation/src/quickopen.ts
  test/smoke/automation/src/workbench.ts
  test/smoke/automation/yarn.lock
  test/smoke/docs/run-locally.md
  test/smoke/package/config.json
  test/smoke/package/package.json
  test/smoke/package/resources/HermesReactNativeSample/build.gradle
  test/smoke/package/resources/launch.json
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/src/debugIos.test.ts
  test/smoke/package/src/helpers/appiumHelper.ts
  test/smoke/package/src/helpers/smokeTestsConstants.ts
  test/smoke/package/src/helpers/utilities.ts
  test/smoke/package/yarn.lock
Labels: js-debug-migration

#1281 Update smoke tests docs
  test/smoke/docs/run-locally.md
Labels: documentation

#1285 Improve async functions control
  src/cdp-proxy/debuggerEndpointHelper.ts
  src/cdp-proxy/reactNativeCDPProxy.ts
  src/common/error/errorStrings.ts
  src/common/error/internalErrorCode.ts
  src/debugger/debugSessionBase.ts
  src/debugger/direct/directDebugSession.ts
  src/debugger/rnDebugSession.ts
Labels: js-debug-migration

#1286 Update extension license to MIT
  release/LICENSE.txt
Labels: documentation

#1287 Prepare for 0.16.0
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease

#1290 Smoke tests migration to vscode 1.45.1
  test/smoke/automation/.gitignore
  test/smoke/automation/package.json
  test/smoke/automation/src/application.ts
  test/smoke/automation/src/code.ts
  test/smoke/automation/src/debug.ts
  test/smoke/automation/src/driver.js
  test/smoke/automation/src/editors.ts
  test/smoke/automation/src/extensions.ts
  test/smoke/automation/src/index.ts
  test/smoke/automation/src/keybindings.ts
  test/smoke/automation/src/playwrightDriver.ts
  test/smoke/automation/src/problems.ts
  test/smoke/automation/src/puppeteerDriver.ts
  test/smoke/automation/src/quickaccess.ts
  test/smoke/automation/src/quickinput.ts
  test/smoke/automation/src/search.ts
  test/smoke/automation/src/settings.ts
  test/smoke/automation/src/statusbar.ts
  test/smoke/automation/src/terminal.ts
  test/smoke/automation/src/workbench.ts
  test/smoke/automation/yarn.lock
  test/smoke/gulpfile.js
  test/smoke/package/config.json
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/src/debugIos.test.ts
Labels: tests

#1291 Improve debug sessions control
  package-lock.json
  package.json
  src/cdp-proxy/reactNativeCDPProxy.ts
  src/debugger/debugSessionBase.ts
  src/debugger/direct/directDebugSession.ts
  src/debugger/rnDebugSession.ts
  src/extension/debugConfigurationProvider.ts
  src/extension/reactNativeSessionManager.ts
  src/extension/rn-extension.ts
  src/extension/rnDebugAdapterDescriptorFactory.ts
Labels: js-debug-migration

#1293 Fix use of "skipFiles" parameter
  src/debugger/debugSessionBase.ts
  src/debugger/direct/directDebugSession.ts
  src/debugger/rnDebugSession.ts
Labels: js-debug-migration

#1292 Adapt smoke tests to dev
  .ci/smoke/smoke-tests-linux.yml
  .ci/smoke/smoke-tests-mac.yml
  .ci/smoke/smoke-tests-windows.yml
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  CHANGELOG.md
  package-lock.json
  package.json
  release/LICENSE.txt
  release/ThirdPartyNotices.txt
  src/common/packager.ts
  src/common/utils.ts
  src/extension/packagerStatusIndicator.ts
  test/smoke/automation/.gitignore
  test/smoke/automation/package.json
  test/smoke/automation/src/application.ts
  test/smoke/automation/src/code.ts
  test/smoke/automation/src/debug.ts
  test/smoke/automation/src/driver.js
  test/smoke/automation/src/editors.ts
  test/smoke/automation/src/extensions.ts
  test/smoke/automation/src/index.ts
  test/smoke/automation/src/keybindings.ts
  test/smoke/automation/src/playwrightDriver.ts
  test/smoke/automation/src/problems.ts
  test/smoke/automation/src/puppeteerDriver.ts
  test/smoke/automation/src/quickaccess.ts
  test/smoke/automation/src/quickinput.ts
  test/smoke/automation/src/search.ts
  test/smoke/automation/src/settings.ts
  test/smoke/automation/src/statusbar.ts
  test/smoke/automation/src/terminal.ts
  test/smoke/automation/src/workbench.ts
  test/smoke/automation/yarn.lock
  test/smoke/docs/run-locally.md
  test/smoke/gulpfile.js
  test/smoke/package/config.json
  test/smoke/package/resources/ExpoSample/App.js
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/src/debugIos.test.ts
  test/smoke/package/src/helpers/appiumHelper.ts
Labels: js-debug-migration, tests
