Repository microsoft/vscode-react-native, pull requests merged in 2020-07, with the labels that each got.

#1329 Fix vulnerabilities
  package-lock.json
  package.json
Labels: security

#1333 Prepare for 0.16.1
  CHANGELOG.md
  package-lock.json
  package.json
  release/ThirdPartyNotices.txt
Labels: prerelease

#1334 [Preview] Fix expo smoke tests
  package.json
  test/smoke/docs/run-locally.md
  test/smoke/package/config.json
  test/smoke/package/resources/ExpoSample/App.js
  test/smoke/package/resources/ExpoSample/App.tsx
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/src/debugIos.test.ts
  test/smoke/package/src/helpers/setupEnvironmentHelper.ts
  test/smoke/package/src/helpers/smokeTestsConstants.ts
  test/smoke/package/src/helpers/utilities.ts
  test/smoke/package/src/main.ts
Labels: preview

#1328 Fix errors in case of spaces in adb path from local.properties
  src/extension/android/adb.ts
  test/extension/android/androidPlatform.test.ts
  test/resources/auxiliaryFiles/templateProject/others/android/local.properties
  test/resources/auxiliaryFiles/templateProject/win/android/local.properties
Labels: preview

#1323 Add experiment service to preview
  package-lock.json
  package.json
  src/common/telemetryHelper.ts
  src/extension/experimentService/IExperiment.ts
  src/extension/experimentService/experimentService.ts
  src/extension/experimentService/experiments/RNTPreviewPrompt.ts
  src/extension/experimentService/experimentsStrings.ts
  test/extension/experimentService/experimentService.test.ts
Labels: preview

#1330 Fix ExponentHelper multi initializing
  src/common/packager.ts
  src/extension/appLauncher.ts
  src/extension/exponent/exponentPlatform.ts
Labels: preview

#1337 Add solution of entry point not exist error for Expo on macOS to Known issues
  README.md
  test/smoke/package/src/helpers/setupEnvironmentHelper.ts
Labels: bug, preview

#1336 Remove Q from the part of the common folder
  src/common/commandExecutor.ts
  src/common/node/fileSystemNode.ts
  src/common/node/package.ts
  src/common/node/promiseNode.ts
  src/common/node/request.ts
  src/common/packager.ts
  src/common/packagerStatus.ts
  src/common/projectVersionHelper.ts
  src/common/reactNativeProjectHelper.ts
  src/debugger/appWorker.ts
  src/debugger/debugSessionBase.ts
  src/debugger/scriptImporter.ts
  src/extension/android/androidPlatform.ts
  src/extension/android/packageNameResolver.ts
  src/extension/exponent/exponentHelper.ts
  src/extension/exponent/exponentPlatform.ts
  src/extension/exponent/xdlInterface.ts
  src/extension/generalMobilePlatform.ts
  src/extension/ios/iOSPlatform.ts
  src/extension/windows/windowsPlatform.ts
  src/typings/exponent/xdl.d.ts
  test/common/projectVersionHelper.test.ts
Labels: preview

#1324 Fix capitalization of GitHub org
  CHANGELOG.md
  README.md
  ThirdPartyNotices.txt
  i18n/chs/package.i18n.json
  i18n/chs/src/common/error/errorStrings.i18n.json
  i18n/cht/package.i18n.json
  i18n/cht/src/common/error/errorStrings.i18n.json
  i18n/csy/package.i18n.json
  i18n/csy/src/common/error/errorStrings.i18n.json
  i18n/deu/package.i18n.json
  i18n/deu/src/common/error/errorStrings.i18n.json
  i18n/esn/package.i18n.json
  i18n/esn/src/common/error/errorStrings.i18n.json
  i18n/fra/package.i18n.json
  i18n/fra/src/common/error/errorStrings.i18n.json
  i18n/ita/package.i18n.json
  i18n/ita/src/common/error/errorStrings.i18n.json
  i18n/jpn/package.i18n.json
  i18n/jpn/src/common/error/errorStrings.i18n.json
  i18n/kor/package.i18n.json
  i18n/kor/src/common/error/errorStrings.i18n.json
  i18n/plk/package.i18n.json
  i18n/plk/src/common/error/errorStrings.i18n.json
  i18n/ptb/package.i18n.json
  i18n/ptb/src/common/error/errorStrings.i18n.json
  i18n/rus/package.i18n.json
  i18n/rus/src/common/error/errorStrings.i18n.json
  i18n/trk/package.i18n.json
  i18n/trk/src/common/error/errorStrings.i18n.json
  package.json
  package.nls.cs.json
  package.nls.de.json
  package.nls.es.json
  package.nls.fr.json
  package.nls.it.json
  package.nls.ja.json
  package.nls.json
  package.nls.ko.json
  package.nls.pl.json
  package.nls.pt-br.json
  package.nls.ru.json
  package.nls.tr.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  release/AdditionalAttributions.txt
  release/ThirdPartyNotices.txt
  src/common/error/errorStrings.ts
  src/common/projectVersionHelper.ts
  src/debugger/forkedAppWorker.ts
  src/debugger/scriptImporter.ts
  src/extension/commandPaletteHandler.ts
  src/typings/q/Q.d.ts
  test/smoke/docs/run-locally.md
Labels: enhancement

#1342 Q package removal from node folder, refactor commandExecutor
  src/common/commandExecutor.ts
  src/common/node/childProcess.ts
  src/common/node/fileSystem.ts
  src/common/node/fileSystemNode.ts
  src/common/node/node.ts
  src/common/node/package.ts
  src/common/node/promise.ts
  src/common/node/promiseNode.ts
Labels: preview

#1341 Fix capitalization of GitHub org
  CHANGELOG.md
  README.md
  ThirdPartyNotices.txt
  i18n/chs/package.i18n.json
  i18n/chs/src/common/error/errorStrings.i18n.json
  i18n/cht/package.i18n.json
  i18n/cht/src/common/error/errorStrings.i18n.json
  i18n/csy/package.i18n.json
  i18n/csy/src/common/error/errorStrings.i18n.json
  i18n/deu/package.i18n.json
  i18n/deu/src/common/error/errorStrings.i18n.json
  i18n/esn/package.i18n.json
  i18n/esn/src/common/error/errorStrings.i18n.json
  i18n/fra/package.i18n.json
  i18n/fra/src/common/error/errorStrings.i18n.json
  i18n/ita/package.i18n.json
  i18n/ita/src/common/error/errorStrings.i18n.json
  i18n/jpn/package.i18n.json
  i18n/jpn/src/common/error/errorStrings.i18n.json
  i18n/kor/package.i18n.json
  i18n/kor/src/common/error/errorStrings.i18n.json
  i18n/plk/package.i18n.json
  i18n/plk/src/common/error/errorStrings.i18n.json
  i18n/ptb/package.i18n.json
  i18n/ptb/src/common/error/errorStrings.i18n.json
  i18n/rus/package.i18n.json
  i18n/rus/src/common/error/errorStrings.i18n.json
  i18n/trk/package.i18n.json
  i18n/trk/src/common/error/errorStrings.i18n.json
  package.json
  package.nls.cs.json
  package.nls.de.json
  package.nls.es.json
  package.nls.fr.json
  package.nls.it.json
  package.nls.ja.json
  package.nls.json
  package.nls.ko.json
  package.nls.pl.json
  package.nls.pt-br.json
  package.nls.ru.json
  package.nls.tr.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  release/AdditionalAttributions.txt
  release/ThirdPartyNotices.txt
  src/common/error/errorStrings.ts
  src/common/projectVersionHelper.ts
  src/debugger/forkedAppWorker.ts
  src/debugger/scriptImporter.ts
  src/extension/commandPaletteHandler.ts
  src/typings/q/Q.d.ts
  test/smoke/docs/run-locally.md
Labels: preview

#1351 Improve Packager status indicator for Preview branch
  package.json
  src/extension/packagerStatusIndicator.ts
Labels: preview

#1354 Q package removal
  gulpfile.js
  package-lock.json
  package.json
  src/common/commandExecutor.ts
  src/common/configurationReader.ts
  src/common/entryPointHandler.ts
  src/common/extensionMessaging.ts
  src/common/hostPlatform.ts
  src/common/node/childProcess.ts
  src/common/node/fileSystem.ts
  src/common/node/package.ts
  src/common/node/promise.ts
  src/common/node/request.ts
  src/common/outputVerifier.ts
  src/common/packager.ts
  src/common/packagerStatus.ts
  src/common/projectVersionHelper.ts
  src/common/reactNativeProjectHelper.ts
  src/common/telemetryGenerators.ts
  src/common/telemetryHelper.ts
  src/debugger/appWorker.ts
  src/debugger/debugSessionBase.ts
  src/debugger/forkedAppWorker.ts
  src/debugger/scriptImporter.ts
  src/debugger/sourceMap.ts
  src/debugger/sourceMapsCombinator.ts
  src/extension/android/adb.ts
  src/extension/android/androidPlatform.ts
  src/extension/android/logCatMonitor.ts
  src/extension/android/packageNameResolver.ts
  src/extension/appLauncher.ts
  src/extension/commandPaletteHandler.ts
  src/extension/exponent/exponentHelper.ts
  src/extension/exponent/exponentPlatform.ts
  src/extension/exponent/xdlInterface.ts
  src/extension/generalMobilePlatform.ts
  src/extension/ios/iOSDebugModeManager.ts
  src/extension/ios/iOSPlatform.ts
  src/extension/ios/plistBuddy.ts
  src/extension/ios/simulatorPlist.ts
  src/extension/launchArgs.ts
  src/extension/openFileAtLocation.ts
  src/extension/reactDirManager.ts
  src/extension/rn-extension.ts
  src/extension/windows/windowsPlatform.ts
  src/extension/windows/wpfPlatform.ts
  src/typings/exponent/xdl.d.ts
  test/common/projectVersionHelper.test.ts
  test/debugger/appWorker.test.ts
  test/debugger/sourceMapsCombinator.test.ts
  test/extension/android/androidPlatform.test.ts
  test/extension/commandExecutor.test.ts
  test/extension/exponent/exponentHelper.test.ts
  test/extension/ios/plistBuddy.test.ts
  test/extension/ios/simulatorPlist.test.ts
  test/resources/processExecution/recording.ts
  test/resources/processExecution/simulator.ts
  test/resources/reactNative022.ts
  test/resources/recordingsHelper.ts
  test/resources/simulators/apkSerializer.ts
Labels: preview

#1320 Start packager before attach to it
  src/debugger/direct/directDebugSession.ts
  src/debugger/rnDebugSession.ts
Labels: preview

#1355 Fix lodash security vulnerability
  test/smoke/package/package.json
  test/smoke/package/yarn.lock
Labels: security, tests

#1358 Fix lodash security vulnerability (preview)
  test/smoke/package/package.json
  test/smoke/package/yarn.lock
Labels: preview

#1357 Add switchable representation for Packager Status Indicator for Preview branch
  package.json
  package.nls.json
  src/common/packager.ts
  src/extension/appLauncher.ts
  src/extension/generalMobilePlatform.ts
  src/extension/packagerStatusIndicator.ts
  src/extension/settingsHelper.ts
Labels: preview
