Repository microsoft/vscode-react-native, pull requests merged in 2020-12, with the labels that each got.

#1455 Overall smoke test refactoring
  .ci/smoke/smoke-tests-common-validation.yml
  .ci/smoke/smoke-tests-linux.yml
  .ci/smoke/smoke-tests-mac.yml
  .ci/smoke/smoke-tests-windows.yml
  README.md
  test/smoke/package/package.json
  test/smoke/package/resources/HermesReactNativeSample/build.gradle
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/src/debugIos.test.ts
  test/smoke/package/src/debugMacOS.test.ts
  test/smoke/package/src/debugWindows.test.ts
  test/smoke/package/src/directDebug.test.ts
  test/smoke/package/src/expoDebug.test.ts
  test/smoke/package/src/helpers/androidEmulatorHelper.ts
  test/smoke/package/src/helpers/androidEmulatorManager.ts
  test/smoke/package/src/helpers/appiumHelper.ts
  test/smoke/package/src/helpers/iosSimulatorHelper.ts
  test/smoke/package/src/helpers/iosSimulatorManager.ts
  test/smoke/package/src/helpers/launchConfigurationManager.ts
  test/smoke/package/src/helpers/setupEnvironmentHelper.ts
  test/smoke/package/src/helpers/smokeTestLogger.ts
  test/smoke/package/src/helpers/smokeTestsConstants.ts
  test/smoke/package/src/helpers/testApplicationSetupManager.ts
  test/smoke/package/src/helpers/testConfigProcessor.ts
  test/smoke/package/src/helpers/utilities.ts
  test/smoke/package/src/helpers/vsCodeHelper.ts
  test/smoke/package/src/helpers/vsCodeManager.ts
  test/smoke/package/src/localization.test.ts
  test/smoke/package/src/main.ts
  test/smoke/package/src/nativeDebug.test.ts
  test/smoke/package/src/otherTests.test.ts
  test/smoke/package/src/smoke.test.ts
  test/smoke/package/yarn.lock
Labels: tests

#1466 Prepare for 1.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: prerelease

#1469 Enhance attach to the debugger documentation
  README.md
Labels: documentation
