Repository microsoft/vscode-react-native, pull requests merged in 2020-09, with the labels that each got.

#1373 Smoke tests update
  .ci/smoke/smoke-tests-linux.yml
  .ci/smoke/smoke-tests-mac.yml
  .ci/smoke/smoke-tests-windows.yml
  .vscode/settings.json
  src/extension/android/androidEmulatorManager.ts
  src/extension/appLauncher.ts
  src/extension/launchScenariosManager.ts
  test/extension/launchScenarioManager.test.ts
  test/smoke/package/config.json
  test/smoke/package/package.json
  test/smoke/package/resources/HermesReactNativeSample/build.gradle
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/src/debugIos.test.ts
  test/smoke/package/src/helpers/androidEmulatorHelper.ts
  test/smoke/package/src/helpers/appiumHelper.ts
  test/smoke/package/src/helpers/utilities.ts
  test/smoke/package/yarn.lock
Labels: tests

#1367 Add iOS direct handler
  .vscode/settings.json
  README.md
  package.json
  package.nls.json
  src/cdp-proxy/CDPMessageHandlers/CDPAPINames.ts
  src/cdp-proxy/CDPMessageHandlers/baseCDPMessageHandler.ts
  src/cdp-proxy/CDPMessageHandlers/hermesCDPMessageHandler.ts
  src/cdp-proxy/CDPMessageHandlers/iOSDirectCDPMessageHandler.ts
  src/cdp-proxy/CDPMessageHandlers/rnCDPMessageHandler.ts
  src/cdp-proxy/debuggerEndpointHelper.ts
  src/cdp-proxy/reactNativeCDPProxy.ts
  src/common/error/errorStrings.ts
  src/common/error/internalErrorCode.ts
  src/common/node/promise.ts
  src/common/packager.ts
  src/common/targetPlatformHelper.ts
  src/debugger/appWorker.ts
  src/debugger/debugSessionBase.ts
  src/debugger/direct/IWDPHelper.ts
  src/debugger/direct/directDebugSession.ts
  src/extension/android/androidPlatform.ts
  src/extension/appLauncher.ts
  src/extension/commandPaletteHandler.ts
  src/extension/debugConfigurationProvider.ts
  src/extension/experimentService/experimentService.ts
  src/extension/exponent/exponentPlatform.ts
  src/extension/ios/iOSPlatform.ts
  src/extension/launchArgs.ts
  src/extension/platformResolver.ts
  src/extension/windows/windowsPlatform.ts
  src/extension/windows/wpfPlatform.ts
  test/cdp-proxy/reactNativeCDPProxy.test.ts
  test/debugger/appWorker.test.ts
  test/extension/android/androidPlatform.test.ts
  test/extension/ios/iOSPlatform.test.ts
  test/resources/processExecution/simulator.ts
  test/smoke/package/src/helpers/utilities.ts
Labels: debugger, enhancement, iOS, preview

#1372 Fix security vulnerabilities in tests
  .ci/smoke/smoke-tests-linux.yml
  .ci/smoke/smoke-tests-mac.yml
  .ci/smoke/smoke-tests-windows.yml
  test/smoke/package/config.json
  test/smoke/package/package.json
  test/smoke/package/resources/HermesReactNativeSample/build.gradle
  test/smoke/package/src/debugAndroid.test.ts
  test/smoke/package/yarn.lock
Labels: security

#1381 Remove TPN copy task
  .ci/common-validation.yml
  .ci/master-pipeline.yml
  .ci/nightly.yml
  .ci/pr-pipeline.yml
  .ci/smoke/smoke-tests-common-validation.yml
  .ci/smoke/smoke-tests-linux.yml
  .ci/smoke/smoke-tests-mac.yml
  .ci/smoke/smoke-tests-windows.yml
Labels: preview

#1383 Decrease delay on debugging stop
  src/debugger/debugSessionBase.ts
  src/debugger/direct/directDebugSession.ts
  src/debugger/rnDebugSession.ts
Labels: preview

#1394 Fix RN Hermes debug configuration
  src/debugger/jsDebugConfigAdapter.ts
Labels: preview

#1397 Update Preview docs
  README.md
Labels: preview

#1395 Preview version fixes
  README.md
  images/custom-host-and-port.png
  images/dev-menu-setup-custom-host.png
  images/select-dev-menu.png
  package.json
  src/common/packager.ts
  src/debugger/appWorker.ts
  src/debugger/jsDebugConfigAdapter.ts
  src/extension/commandPaletteHandler.ts
  src/extension/ios/iOSSimulatorManager.ts
  src/extension/windows/windowsPlatform.ts
Labels: preview

#1404 Prepare for 1.0.0
  CHANGELOG.md
  release/ThirdPartyNotices.txt
Labels: prerelease
